version: 2

project_name: countdown

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: countdown
    main: .
    binary: countdown
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: countdown
    repository:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
    description: "CLI countdown timer with spinner animation"
    license: "MIT"
    install: |
      bin.install "countdown"
    test: |
      system "#{bin}/countdown", "--version"
    skip_upload: auto
