# typed: false
# frozen_string_literal: true

# Homebrew formula for countdown CLI
# This formula is auto-generated by GoReleaser
# Manual installation: brew install <owner>/tap/countdown
class Countdown < Formula
  desc "CLI countdown timer with spinner animation"
  homepage "https://github.com/OWNER/countdown"
  license "MIT"
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/OWNER/countdown/releases/download/v#{version}/countdown_#{version}_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER"
    end

    on_arm do
      url "https://github.com/OWNER/countdown/releases/download/v#{version}/countdown_#{version}_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/OWNER/countdown/releases/download/v#{version}/countdown_#{version}_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER"
    end

    on_arm do
      url "https://github.com/OWNER/countdown/releases/download/v#{version}/countdown_#{version}_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    bin.install "countdown"
  end

  test do
    system "#{bin}/countdown", "--version"
  end
end
